CREATE OR REPLACE FUNCTION HR.FN_COUNTRIES(P_COUNTRY_ID     IN   COUNTRIES.COUNTRY_ID%TYPE) 
  RETURN COUNTRIES.COUNTRY_NAME%TYPE
IS
  CURSOR cur_countries(C_COUNTRY_ID   COUNTRIES.COUNTRY_ID%TYPE) IS 
    SELECT COUNTRY_NAME FROM COUNTRIES
      WHERE COUNTRY_ID = C_COUNTRY_ID;
      
  V_COUNTRY_NAME    COUNTRIES.COUNTRY_NAME%TYPE;

BEGIN
  OPEN cur_countries(P_COUNTRY_ID);
  FETCH cur_countries INTO V_COUNTRY_NAME;

  RETURN V_COUNTRY_NAME;
END FN_COUNTRIES;