CREATE OR REPLACE PROCEDURE SP_COUNTRIES(P_COUNTRY_ID     IN   COUNTRIES.COUNTRY_ID%TYPE,
                                         P_COUNTRY_NAME   OUT  COUNTRIES.COUNTRY_NAME%TYPE) 
IS
  CURSOR cur_countries(C_COUNTRY_ID   COUNTRIES.COUNTRY_ID%TYPE) IS 
    SELECT COUNTRY_ID, COUNTRY_NAME FROM COUNTRIES
      WHERE COUNTRY_ID = C_COUNTRY_ID;
      
  V_COUNTRY_ID    COUNTRIES.COUNTRY_ID%TYPE;
  V_COUNTRY_NAME    COUNTRIES.COUNTRY_NAME%TYPE;

BEGIN
  OPEN cur_countries('BR');
  FETCH cur_countries INTO V_COUNTRY_ID, V_COUNTRY_NAME;

  P_COUNTRY_NAME := V_COUNTRY_NAME;
END SP_COUNTRIES;
